### ISSUE TITLE
Any support for ARM

### ISSUE THREAD

**Issue by srikanth007m** [oere/FIRESTARTER-oere#1]
Hi, 

I see FIRESTARTER is supporting only x86 archs. Is it possible to have it for ARM as well? It would be helpful for the users like me

**Comment by oere** [comment]
@srikanth007m please contact the original author(s) of the software at 

-  https://github.com/tud-zih-energy/FIRESTARTER

-  https://tu-dresden.de/die_tu_dresden/zentrale_einrichtungen/zih/forschung/projekte/firestarter/
